services:
  patients:
    image: mediscreen-patients:1.0.0
    ports:
      - 8081:8081
  notes:
    image: mediscreen-notes:1.0.0
    ports:
      - 8082:8082
  reports:
    image: mediscreen-reports:1.0.0
    ports:
      - 8080:8080
  mysql:
    image: mysql:8.0.24
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: patients
      MYSQL_ROOT_PASSWORD: OpenClassrooms42!
  mongo:
    image: mongo:4.4.4-bionic
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: notesUser
      MONGO_INITDB_ROOT_PASSWORD: P10Notes!
      MONGO_INITDB_DATABASE: note