services:
  patients:
    image: mediscreen-patients:1.0.0
    ports:
      - 8081:8080
    depends_on:
      - mysql
  notes:
    image: mediscreen-notes:1.0.0
    ports:
      - 8082:8080
    depends_on:
      - mongo
      - patients
  reports:
    image: mediscreen-reports:1.0.0
    ports:
      - 8083:8080
    depends_on:
      - patients
      - notes
  mysql:
    image: mysql:5.7.33
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: patients
      MYSQL_USER: root
      MYSQL_PASSWORD: FundTransferP6!
  mongo:
    image: mongo:4.4.4-bionic
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: notesUser
      MONGO_INITDB_ROOT_PASSWORD: P10Notes!
      MONGO_INITDB_DATABASE: note